PROC SQL;
	CREATE VIEW WORK.SORTTempTableSorted AS
		SELECT 
			T.psych_admits_90d
			, CASE WHEN T.Sex = 'Male' THEN 1 ELSE 0 END AS male
			, CASE WHEN T.race_eth = 'white' THEN 1 ELSE 0 END AS white
			, CASE WHEN T.insurance = 'medicaid' THEN 1 ELSE 0 END AS medicaid
			, T.Homeless
			, T.SUD_dx
	FROM WORK.PAPER_DATA as T
;
QUIT;
TITLE;
TITLE1 "Logistic Regression Results";
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";
PROC LOGISTIC DATA=WORK.SORTTempTableSorted
		PLOTS(ONLY)=NONE
	;
	CLASS male 	(REF = '0') white 	(REF = '0') medicaid 	(REF = '0') Homeless 	(REF = '0') SUD_dx 	(REF = 'False');
	MODEL psych_admits_90d (Event = '1')=male white medicaid Homeless SUD_dx		/
		SELECTION=NONE
		LINK=LOGIT
	;
RUN;
QUIT;

/* -------------------------------------------------------------------
   End of task code
   ------------------------------------------------------------------- */
RUN; QUIT;
%_eg_conditional_dropds(WORK.SORTTempTableSorted);
TITLE; FOOTNOTE;
ODS GRAPHICS OFF;


